### ISSUE TITLE
ErrorException: Array to string conversion

### ISSUE THREAD

**Issue by MarinX** [yuansfer/yuansfer-php-sdk#3]
In abstract class [AbstractApi](https://github.com/yuansfer/yuansfer-php-sdk/blob/master/src/Api/AbstractApi.php), method [addRequired](https://github.com/yuansfer/yuansfer-php-sdk/blob/master/src/Api/AbstractApi.php#L59), array_unique takes the array of array param for [SecurePay](https://github.com/yuansfer/yuansfer-php-sdk/blob/master/src/Api/SecurePay.php) class.

```php
$this->addRequired(array(
            array('amount', 'rmbAmount'),
            'currency',
            'vendor',
            'ipnUrl',
            'callbackUrl',
            'terminal',
            'reference',
        ));
```

and addRequired method
```php
protected function addRequired($fields)
    {
        static::$required = \array_unique(
            \array_merge(static::$required, (array) $fields)
        );
    }
```

Will throw exception since the default sorting method for `array_unique` is string.

Proposed solution:
Add `SORT_REGULAR` to `array_unique` optional param(`sort_flags`).

Let me know if you want me to create a PR for it.
Thanks,

**Comment by flyinghail** [comment]
Thanks @MarinX, i have fixed it
