### ISSUE TITLE
Why is Process API missing in Yuansfer PHP SDK version 3.0.3?

### ISSUE THREAD

**Issue by datbachkhoa** [yuansfer/yuansfer-php-sdk#5]
Hi Team, 

I am trying to call the [BrainTree](https://docs.yuansfer.com/api-reference-v3/payments/online-payment/yuansfer-integrated-payment/braintree-payments) API and you instruct me to use $yuansfer->createProcess(). But I found that this function as well as the API Object Process are missing in version 3.0.3. They are only in master branch.
![image](https://github.com/yuansfer/yuansfer-php-sdk/assets/5513089/6cce0b8d-6260-4504-950f-cc7cbdb7aa50)
![image](https://github.com/yuansfer/yuansfer-php-sdk/assets/5513089/f52f28db-81d1-4abc-b26a-04db8957c576)

The problem is that when I use composer to install your library, I cannot retrieve the master branch. So why are they missing in version 3.0.3? 

Thanks and Best regards.

**Comment by flyinghail** [comment]
This API has been added to the just released [v3.0.4](https://github.com/yuansfer/yuansfer-php-sdk/releases/tag/v3.0.4)
